# Application configuration
# Use <<project_root> as placeholder for the project root directory

logging:
  log_level: INFO
  log_folder: <<project_root>>/logs/

postgres:
  path_to_postgres: "A:/PostgreSQL/16"
  username: technical_user
  password: postgresql
  port: 5432
  host: 127.0.0.1
  database: ml_trader_db

webserver:
  host: 127.0.0.1
  port: 5000
  debug_mode: False

tradeable_symbols: ["BTCUSD","ETHUSD"]
trading_fees: 0.00 # No calculation can be performed here | #TODO Lookup trading fees on Bybit

price_update_interval: 15

path_to_models: <<project_root>>/models/saved_models/ # don't use quotes here

technical_indicators:
  indicators: ["moving_average", "exponential_moving_average", "moving_std", "periodic_highs", "periodic_lows", "bollinger_bands", "macd", "rsi", "momentum"]

  moving_average:
    period: 20

  exponential_moving_average:
    period: 20

  moving_std:
    period: 20

  periodic_highs:
    period: 20

  periodic_lows:
    period: 20

  bollinger_bands:
    period: 20
    std_dev: 1

  macd:
    longer: 26
    shorter: 12

  rsi:
    period: 14

  momentum:
    period: 10
