# Application configuration
# Use <<project_root> as placeholder for the project root directory

logging:
  log_level: DEBUG
  log_folder: <<project_root>>/logs/

postgres:
  username: technical_user
  password: postgresql
  port: 5432
  host: 127.0.0.1
  database: financial_data
  tables:

technical_indicators:
  indicators: ["moving_average", "exponential_moving_average", "moving_std", "periodic_highs", "periodic_lows", "bollinger_bands", "macd", "rsi", "momentum"]

  moving_average:
    period: 20

  exponential_moving_average:
    period: 20

  moving_std:
    period: 20

  periodic_highs:
    period: 20

  periodic_lows:
    period: 20

  bollinger_bands:
    period: 20
    std_dev: 1

  macd:
    longer: 26
    shorter: 12

  rsi:
    period: 14

  momentum:
    period: 10
